### ISSUE TITLE
Weird server lag and error

### ISSUE THREAD

**Issue by Govindass** [Gerrygames/ViaRewind#69]
I have no idea what happened, but out of nowhere all players left and server started being very laggy, like commands which I type in console only get executed minute later or so, I got this error during it:
[13:05:46 WARN]: java.lang.NullPointerException
[13:05:46 WARN]:        at de.gerrygames.viarewind.utils.PacketUtil$1.run(PacketUtil.java:41)
[13:05:46 WARN]:        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
[13:05:46 WARN]:        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
[13:05:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:05:46 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[13:05:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:05:46 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Govindass** [comment]
had it happening again, it happened just after player shot me with a bow and I got launched far up in sky(which is unnormal, but unsure if that's viarewind problem)
but I have got shot by bow many other times without it happening
it was 30sec lagspike with the same error as above

**Comment by Gerrygames** [comment]
This error should only occur if the player connection was unexpectedly closed for some reason. ViaRewind is only acting on a protocol level and not running any heavy tasks in the main thread. It should not cause any server to lag massively.
